---
- name: Launch front
  community.docker.docker_container:
    name: front
    image: "{{ docker_hub_user }}/tp-devops-front:latest"
    pull: true
    state: started
    restart_policy: unless-stopped
    networks:
      - name: app-network
