LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

ProxyPreserveHost On

ProxyPass /api/ http://app:8080/
ProxyPassReverse /api/ http://app:8080/

ProxyPass / http://front:80/
ProxyPassReverse / http://front:80/